---
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Apptainer
        run: |
          export VERSION=1.0.2
          wget https://github.com/apptainer/apptainer/releases/download/v${VERSION}/apptainer_${VERSION}_amd64.deb
          sudo apt-get install -y ./apptainer_${VERSION}_amd64.deb
          rm -r apptainer_${VERSION}_amd64.deb

      - name: Build pytorch GAN zoo
        working-directory: workflows/pytorch_GAN_zoo/
        run: |
          sudo env "PATH=$PATH" python3 --version
          sudo env "PATH=$PATH"  ./build.sh
