---
name: Idempotence

on: [push]

jobs:
  batch_scripts:
    name: "Batch Script Idempotence"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Generate batch scripts
        working-directory: ./workflows
        run: ./template_batch_scripts.py

      - name: Check idempotence
        run: |
          if [ $(git diff | wc -l) != 0 ]; then
          false
          fi
